biblioteca/config/routes.rb
Rails.application.routes.draw do
  resources :rents

  resources :books
  
  devise_for :users

  get '/login', to: 'authentication#authenticate' 

  root :to => "books#index"

end

biblioteca/app/models/book.rb
class Book < ActiveRecord::Base
	validates_presence_of :nome, message: " deve ser preenchido"
	validates_presence_of :autor, message: " deve ser preenchido"
 
	validates_numericality_of :quantidade_estoque, greater_than: 0.9, message: " deve ser de no mínimo 1"

  	self.per_page = 10

  	def self.search(search, id)
   		where(['nome LIKE ? or autor LIKE ?', "%#{search}%", "%#{search}%"])
	end
end

biblioteca/app/models/rent.rb
class Rent < ActiveRecord::Base
	belongs_to :user
	belongs_to :book
end

biblioteca/app/models/user.rb
class User < ActiveRecord::Base
	validates_presence_of :nome, message: " deve ser preenchido"

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

biblioteca/app/controllers/application_controller.rb
	class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_filter :http_basic_authenticate
  skip_before_filter :verify_authenticity_token

	def http_basic_authenticate
	   if request.format == :json
	    	authenticate_or_request_with_http_basic do |email, password|
	       		@current_user = User.find_for_database_authentication(:email => URI.unescape(email))
	       		@current_user.present? ? @current_user.valid_password?(password) : false
	     	end
	   end
	end


  protected
 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :nome, :endereco, :secret_p) }
   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:id, :password, :password_confirmation, :secret_p) }
 end
end

biblioteca/app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
	before_filter :http_basic_authenticate
	def authenticate
		@user = current_user
		respond_to do |format|
			format.json 
		end
	end
end

biblioteca/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show, :edit]
  # skip_before_filter :http_basic_authenticate, only: [:index]

  def index
    @books = Book.order('created_at DESC').page(params[:page]).per_page(10).search(params[:search], params[:id])
    respond_to do |format|
      format.json
      format.html
    end
  end

  def show
    @book = Book.find(params[:id])
    respond_to do |format|
      format.json
      format.html
    end
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    books = Book.all
    current_nome = book_params[:nome]
    current_autor = book_params[:autor]
    current_qtd = book_params[:quantidade_estoque].to_i

    if Book.last
      books.each do |b|
        if b.nome == current_nome && b.autor == current_autor
          if current_qtd >=1
            b.update(quantidade_estoque: b.quantidade_estoque.to_i+current_qtd.to_i)
            redirect_to books_url, notice: 'Livro já existente, estoque expandido'
          else
            redirect_to books_url, notice: 'Livro já existente'
          end
          break
        elsif b == (Book.last)
          save_book
        end
      end
    else
      save_book
    end
  end

  def update
    books = Book.all
    current_nome = book_params[:nome]
    current_autor = book_params[:autor]
    current_qtd = book_params[:quantidade_estoque].to_i
    current_id = params[:id]

    books.each do |b|
      if b.nome == current_nome && b.autor == current_autor && (b.id != current_id.to_i)
        redirect_to edit_book_url, notice: 'Livro já existente'
        break
      elsif b == (Book.last)
        update_finish_book
      end
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Livro removido' }
      format.json { head :no_content }
    end
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:nome, :autor, :descricao, :quantidade_estoque)
    end

    def save_book
      @book = Book.new(book_params)
      respond_to do |format|
        if @book.save
          format.html {redirect_to @book, notice: 'Livro registrado com sucesso'}
          format.json { render :show, status: :created, location: @book }
        else
          format.html {render action: 'new'}
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      end
    end

    def update_finish_book
      @book = Book.find(params[:id])
      respond_to do |format|
        if @book.update(book_params)
          format.html { redirect_to @book, notice: 'Livro modificado'}
          format.json { render :show, status: :ok, location: @book }
        else
          format.html { render action: 'edit'}
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      end
    end
end

biblioteca/app/controllers/rents_controller.rb
class RentsController < ApplicationController
  before_action :set_rent, only: [:show, :edit, :update, :destroy]
  #rails g scaffold rent user:references book:references status:boolean --migration=false -s

  # GET /rents
  # GET /rents.json
  def index
    @rents = Rent.all.where(user_id: current_user.id)
    # puts "--------------------------------------------------#{@rents.count}"
    respond_to do |format|
      format.json
      format.html
    end
  end

  # GET /rents/1
  # GET /rents/1.json
  def show
  end

  # GET /rents/new
  def new
    @rent = Rent.new
  end

  # GET /rents/1/edit
  def edit
  end

  # POST /rents
  # POST /rents.json
  def create
    @rent = Rent.new(rent_params)

    respond_to do |format|
      if @rent.save
        update_book rent_params[:book_id]
        format.html { redirect_to rents_url, notice: 'Rent was successfully created.' }
        format.json { render :show, status: :created, location: @rent }
      else
        format.html { render :new }
        format.json { render json: @rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rents/1
  # PATCH/PUT /rents/1.json
  def update
    respond_to do |format|
      if @rent.update(rent_params)
        format.html { redirect_to @rent, notice: 'Rent was successfully updated.' }
        format.json { render :show, status: :ok, location: @rent }
      else
        format.html { render :edit }
        format.json { render json: @rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rents/1
  # DELETE /rents/1.json
  def destroy
    update_delete_book @rent.book_id
    @rent.destroy    
    respond_to do |format|
      format.html { redirect_to rents_url, notice: 'Rent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rent
      @rent = Rent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rent_params
      params.require(:rent).permit(:user_id, :book_id, :status)
    end

    def update_book book_id
      b = Book.find(book_id)
      b.update(quantidade_alugada: b.quantidade_alugada.to_i+1)
    end

    def update_delete_book book_id
      b = Book.find(book_id)
      b.update(quantidade_alugada: b.quantidade_alugada.to_i-1)
    end
end

biblioteca/app/helpers/application_helper.rb
module ApplicationHelper
end

biblioteca/app/helpers/book_helper.rb
module BookHelper
end

biblioteca/app/helpers/rents_helper.rb
module RentsHelper
end

biblioteca/app/views/books/_form.html.erb
<%= form_for (@book) do |f| %>
<% if @book.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@book.errors.count, "Erro") %> - Confira os dados: </h2>

	<ul>
		<% @book.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>
<br>
<div class="field">
	<%= f.label :nome %>
	<%= f.text_field :nome, autofocus: true %>
</div><br/>
<div class="field">
	<%= f.label :autor %>
	<%= f.text_field :autor %>
</div><br/>
<div class="field">
	<%= f.label :quantidade %>
	<%= f.text_field :quantidade_estoque %>
</div><br/>
<div class="field">
	<%= f.label :descricao %>
	<%= f.text_area :descricao, size:"23" %>
</div>
<p class="actions">
	<%= f.submit 'Registrar' %>
</p>
<% end %>

biblioteca/app/views/books/create.html.erb
<h1>Book#create</h1>
<p>Find me in app/views/book/create.html.erb</p>

biblioteca/app/views/books/destroy.html.erb
<h1>Book#destroy</h1>
<p>Find me in app/views/book/destroy.html.erb</p>

biblioteca/app/views/books/edit.html.erb
<div  class="book_form">
	<fieldset>
		<legend>Realize as Alterações</legend>
		<%= render 'form' %>
		&nbsp;&nbsp;<%= link_to '← Voltar', books_path %>
	</fieldset>
</div>

biblioteca/app/views/books/index.html.erb
 <div><%= form_tag books_path, :method => 'get'  do %>
   <%= text_field_tag :search, params[:search]%>
   <%= submit_tag "Buscar", :nome => nil  %><a></a>
 <% end %>
</div>

<%= will_paginate @posts, :style => 'color:#458B74' %>

<% @books.each do |book| %>
	<div id="form_book">
		<form class="form_first">
			<legend><%=book.nome %></legend>
			<br>
			&nbsp;<font >Autor:</font>
			&nbsp;<%=truncate(strip_tags(book.autor),size:1) %>
			<p>&nbsp;Disponíveis:&nbsp;<%=(book.quantidade_estoque.to_i)-(book.quantidade_alugada.to_i) %></p>
			<p>&nbsp;<%= link_to '( Detalhes )', book %></p>

			<% if user_signed_in? %>
				<% rents = Rent.all.where(user_id: current_user.id) %>
				<% if rents.last %>
					<% rents.each do |r| %>
						<% if r.book_id == book.id %>
							<p align="right"><%= image_tag("alugado.png", class: 'image_alugar')%></p>
							<% break %>
						<% end %>

						<% if r.book_id != book.id && (book.quantidade_estoque.to_i)-(book.quantidade_alugada.to_i) <= 0 && r  == rents.last %>
							<p align="right"><%= image_tag("esgotado.png", class: 'image_alugar')%></p>
							<% break %>
						<% end %>

						<% if r.book_id != book.id && (book.quantidade_estoque.to_i)-(book.quantidade_alugada.to_i) > 0 && r  == rents.last %>
							&nbsp;&nbsp;<%= link_to image_tag("alugar_bottom.png", class: 'image_alugar'), rents_path(rent: {user_id: current_user, book_id: book, status: true}), method: :create, data: { confirm: 'Deseja realmente alugar?'} %>
							<% break %>
						<% end %>
					<% end %>
				<% else %>
					<% if (book.quantidade_estoque.to_i)-(book.quantidade_alugada.to_i) <= 0 %>
						<p align="right"><%= image_tag("esgotado.png", class: 'image_alugar')%></p>
					<% else %>
					&nbsp;&nbsp;<%= link_to image_tag("alugar_bottom.png", class: 'image_alugar'), rents_path(rent: {user_id: current_user, book_id: book, status: true}), method: :create, data: { confirm: 'Deseja realmente alugar?'} %>
					<% end %>
				<% end %>
			<% end %>
		</form>
	</div>
<% end %>

biblioteca/app/views/books/new.html.erb
<div class="book_form">
	<fieldset>
		<legend>Novo Livro</legend>
			<%= render 'form' %>
			&nbsp;&nbsp;<%= link_to '← Voltar', books_path %>
	</fieldset>
</div>

biblioteca/app/views/books/restaurante_params.html.erb
<h1>Book#restaurante_params</h1>
<p>Find me in app/views/book/restaurante_params.html.erb</p>

biblioteca/app/views/books/set_restaurante.html.erb
<h1>Book#set_restaurante</h1>
<p>Find me in app/views/book/set_restaurante.html.erb</p>

biblioteca/app/views/books/show.html.erb
<div class="book_form">
	<fieldset>
		<legend><%= @book.nome %></legend><br>
		<div>&nbsp;&nbsp;<b>Autor:&nbsp;&nbsp;</b><%= @book.autor %></div><br>

		<div>&nbsp;&nbsp;<b>Qtd. em  Estoque:&nbsp;&nbsp;</b><%= @book.quantidade_estoque %></div><br>

		<div>&nbsp;&nbsp;<b>Alugados:</b>&nbsp;&nbsp;<%= @book.quantidade_alugada %></div><br>

		<div>&nbsp;&nbsp;<textarea , cols="40" rows="5"  readonly="readonly"><%= @book.descricao %></textarea></div><br />
		
		<p><%= link_to 'Editar', edit_book_path(@book) %>&nbsp; - &nbsp;<%= link_to 'Excluir', @book, method: :delete, data: {confirm: 'Você tem certeza?'} %><br></p>

		&nbsp;&nbsp;<%= link_to '← Voltar', books_path %>
	</fieldset>
</div>

biblioteca/app/views/books/update.html.erb
<h1>Book#update</h1>
<p>Find me in app/views/book/update.html.erb</p>

biblioteca/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title> Biblioteca Online</title>
		<title>Biblioteca</title>
		<%= stylesheet_link_tag "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>	
		<div id="banner">
			<%= image_tag("logo.png") %>
			Biblioteca Online
		</div>
		<div id="columns">
					<div id="side"><font color="#FFFFFF">
						<fieldset>
     						<div align="center">
     							<% if user_signed_in? %>
     							<legend><%= current_user.nome %></legend>
    							<p>
    								<%= link_to image_tag("pasta_livros.png", class: 'size_icon'),rents_path %>&nbsp;
    								<%= link_to image_tag("home.png", class: 'size_icon'),books_path %>&nbsp;
    								<%= link_to image_tag("log_out.png", class: 'size_icon'), destroy_user_session_path, method: :delete, data: {confirm: 'Deseja realmente sair?'} %></p>
    							<% else %>
    								<ul>	
										<li><b><%= link_to "Registrar-se", new_user_registration_path %></b> <i>ou</i> <b><%= link_to "Logar", new_user_session_path %></b></li>
									</ul>
    						<% end %></font>
    					</div>
    					</fieldset>
    					<% if user_signed_in? %>
	    					<ul>
								<li><%= image_tag "nextn.png", class: 'size_icon_small' %><i><%= link_to '      Registrar um Livro', new_book_path %></i></li>
								<li><%= image_tag "nextn.png", class: 'size_icon_small' %><i><%= link_to '      Meus Livros', rents_path %></i></li>
							</ul>
    					<% end %>
    				</div>
			<div id="main">
				<%= yield %>
			</div>
		</div>
	</body>
</html>

biblioteca/app/views/rents/_form.html.erb
<%= form_for(@rent) do |f| %>
  <% if @rent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rent.errors.count, "error") %> prohibited this rent from being saved:</h2>

      <ul>
      <% @rent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id%>
  </div>
  <div class="field">
    <%= f.label :book_id %><br>
    <%= f.text_field :book_id%>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit 'Confirmar Agendamento'%>
  </div>
<% end %>

biblioteca/app/views/rents/edit.html.erb
<h1>Editing rent</h1>

<%= render 'form' %>

<%= link_to 'Show', @rent %> |
<%= link_to 'Back', rents_path %>

biblioteca/app/views/rents/index.html.erb
<div class="book_form">
  <fieldset>
  <legend>Meus Livros</legend>
  <% if @rents.last%>
    <br>
    <table>
      <tr>
        <th>Nome</th>
        <th>Autor</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

      <tbody>
        <% @rents.each do |rent| %>
          <% if rent.book %>
            <tr>
              <td>&nbsp;<%= rent.book.nome %>&nbsp;&nbsp;</td>
              <td>&nbsp;&nbsp;<%= rent.book.autor %>&nbsp;&nbsp;</td>
              <td>&nbsp;&nbsp;<%= link_to 'Fazer a devolução', rent, method: :delete, data: { confirm: 'Deseja realmente devolver o Livro?' } %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>

      <br>
      &nbsp;&nbsp;<%= link_to '← Voltar', books_path %>
    <% else %>
      <br>
      <p>&nbsp;&nbsp;&nbsp;Nenhum Livro alugado...</p>
      &nbsp;&nbsp;<%= link_to '← Voltar', books_path %>
    <% end %>
  </fieldset>
</div>

biblioteca/app/views/rents/new.html.erb
<h1>New rent</h1>

<%= render 'form' %>

<%= link_to 'Back', rents_path %>

biblioteca/app/views/rents/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>User:</strong>
  <%= @rent.user_id %>
</p>

<p>
  <strong>Book:</strong>
  <%= @rent.book_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @rent.status %>
</p>

<%= link_to 'Edit', edit_rent_path(@rent) %> |
<%= link_to 'Back', books_path %>